name: Build & Deploy Flutter App to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build Flutter Webapp
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.1'

    - name: Build Webapp
      working-directory: ./
      run: |
        flutter pub get
        flutter build web

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:geosentry
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT }}
        PROJECT_PATH: ./
